import React from 'react';
import { BarChart3, Info, AlertCircle, TrendingUp, TrendingDown, Layers } from 'lucide-react';
import {
  BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, ReferenceLine, Cell
} from 'recharts';
import { ShapFeature } from '@/types';

interface EvidenceAttributionPanelProps {
  shapSummary?: {
    baseValue?: number;
    features: ShapFeature[];
  };
}

export function EvidenceAttributionPanel({ shapSummary }: EvidenceAttributionPanelProps) {
  const hasFeatures = shapSummary?.features && shapSummary.features.length > 0;

  if (!hasFeatures) {
    return (
      <div className="space-y-4 rounded-[var(--radius-lg)] border border-slate-border bg-slate-surface p-5">
        <div className="flex items-center justify-between border-b border-slate-border-subtle pb-3">
          <div className="flex items-center space-x-2">
            <BarChart3 className="h-4 w-4 text-[var(--color-clinical-400)]" aria-hidden="true" />
            <h3 className="text-xs font-semibold uppercase tracking-wide text-slate-text-primary">Model feature attribution (SHAP)</h3>
          </div>
        </div>

        <div className="flex min-h-[260px] flex-col items-center justify-center space-y-2 rounded-[var(--radius-md)] border border-slate-border-subtle bg-slate-inset p-6 text-center">
          <div className="flex h-10 w-10 items-center justify-center rounded-full bg-slate-inset text-slate-text-muted">
            <Info className="h-5 w-5" aria-hidden="true" />
          </div>
          <h4 className="text-xs font-semibold text-slate-text-secondary">Feature attribution unavailable</h4>
          <p className="max-w-md text-xs leading-relaxed text-slate-text-muted">
            SHAP feature attribution weights were not generated by the backend for this case. This interface does
            not display fabricated or simulated feature importance scores.
          </p>
        </div>
      </div>
    );
  }

  const chartData = (shapSummary?.features || []).map((f) => ({
    feature: f.feature,
    importance: f.importance,
    category: f.category || 'General',
    fill: f.importance >= 0 ? '#4da3f5' : '#c4364c',
  }));

  return (
    <div className="space-y-4 rounded-[var(--radius-lg)] border border-slate-border bg-slate-surface p-5">
      <div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-border-subtle pb-3">
        <div className="flex items-center space-x-2">
          <BarChart3 className="h-4 w-4 text-[var(--color-clinical-400)]" aria-hidden="true" />
          <h3 className="text-xs font-semibold uppercase tracking-wide text-slate-text-primary">Model feature attribution (SHAP)</h3>
        </div>
        <div className="flex items-center space-x-2 text-[10px]">
          <span className="inline-flex items-center space-x-1 rounded border border-[var(--color-clinical-700)] bg-[var(--color-clinical-950)] px-2 py-0.5 font-semibold text-[var(--color-clinical-300)]">
            <TrendingUp className="h-3 w-3" aria-hidden="true" />
            <span>Supports</span>
          </span>
          <span className="inline-flex items-center space-x-1 rounded border border-[var(--color-safety-critical-border)] bg-[var(--color-safety-critical-bg)] px-2 py-0.5 font-semibold text-[var(--color-safety-critical)]">
            <TrendingDown className="h-3 w-3" aria-hidden="true" />
            <span>Restricts</span>
          </span>
        </div>
      </div>

      <div className="h-[340px] w-full pt-2">
        <ResponsiveContainer width="100%" height="100%">
          <BarChart layout="vertical" data={chartData} margin={{ top: 5, right: 25, left: 10, bottom: 5 }}>
            <XAxis
              type="number"
              domain={[-0.3, 0.5]}
              tick={{ fontSize: 10, fill: '#7c8aa8' }}
              tickFormatter={(val) => `${val > 0 ? '+' : ''}${val.toFixed(2)}`}
            />
            <YAxis dataKey="feature" type="category" width={160} tick={{ fontSize: 9, fill: '#a9b6cc' }} />
            <Tooltip
              content={({ active, payload }) => {
                if (active && payload && payload.length) {
                  const data = payload[0].payload;
                  return (
                    <div className="space-y-1 rounded-[var(--radius-md)] border border-slate-border bg-slate-canvas p-2.5 text-xs text-white shadow-xl">
                      <p className="font-semibold text-slate-text-primary">{data.feature}</p>
                      <div className="flex items-center justify-between space-x-4 text-[11px]">
                        <span className="text-slate-text-muted">SHAP weight:</span>
                        <span className={`num-clinical font-semibold ${data.importance >= 0 ? 'text-[var(--color-clinical-400)]' : 'text-[var(--color-safety-critical)]'}`}>
                          {data.importance > 0 ? '+' : ''}
                          {data.importance.toFixed(4)}
                        </span>
                      </div>
                      {data.category && (
                        <p className="border-t border-slate-border-subtle pt-1 text-[10px] text-slate-text-muted">
                          Category: {data.category}
                        </p>
                      )}
                    </div>
                  );
                }
                return null;
              }}
            />
            <ReferenceLine x={0} stroke="#7c8aa8" strokeDasharray="3 3" />
            <Bar dataKey="importance" radius={[0, 4, 4, 0]}>
              {chartData.map((entry, index) => (
                <Cell key={`cell-${index}`} fill={entry.fill} />
              ))}
            </Bar>
          </BarChart>
        </ResponsiveContainer>
      </div>

      {typeof shapSummary?.baseValue === 'number' && (
        <div className="num-clinical flex items-center justify-between border-t border-slate-border-subtle pt-2 text-[11px] text-slate-text-muted">
          <span>Expected base value (E[f(x)]): <strong className="text-slate-text-secondary">{shapSummary.baseValue.toFixed(3)}</strong></span>
          <span>{chartData.length} evaluated features</span>
        </div>
      )}
    </div>
  );
}
