import React from 'react';
import { Layers, Pill, ShieldCheck, AlertTriangle, Route, Calendar } from 'lucide-react';
import { AlternativeRecommendation } from '@/types';

interface AlternativeRecommendationsListProps {
  alternatives: AlternativeRecommendation[];
}

export function AlternativeRecommendationsList({ alternatives }: AlternativeRecommendationsListProps) {
  if (!alternatives || alternatives.length === 0) {
    return (
      <div className="p-5 rounded-[var(--radius-lg)] bg-slate-surface border border-slate-border space-y-2">
        <div className="flex items-center space-x-2">
          <Layers className="w-4 h-4 text-[var(--color-clinical-400)]" />
          <h3 className="text-xs font-semibold uppercase tracking-wider text-slate-text-primary">
            Alternative Antimicrobial Recommendations
          </h3>
        </div>
        <p className="text-xs text-slate-text-muted italic p-3 bg-slate-inset rounded-[var(--radius-md)] border border-slate-border-subtle">
          No alternative antimicrobial regimens were generated by the CDSS backend for this profile.
        </p>
      </div>
    );
  }

  const getAwareBadge = (cat: string) => {
    const norm = (cat || '').toLowerCase();
    if (norm === 'access') {
      return (
        <span className="inline-flex items-center space-x-1 px-2.5 py-0.5 rounded-full text-[10px] font-semibold bg-[var(--color-safety-success-bg)] text-[var(--color-safety-success)] border border-[var(--color-safety-success-border)]">
          <ShieldCheck className="w-3 h-3 text-[var(--color-safety-success)]" />
          <span>AWaRe: ACCESS</span>
        </span>
      );
    }
    if (norm === 'watch') {
      return (
        <span className="inline-flex items-center space-x-1 px-2.5 py-0.5 rounded-full text-[10px] font-semibold bg-[var(--color-safety-warning-bg)] text-[var(--color-safety-warning)] border border-[var(--color-safety-warning-border)]">
          <AlertTriangle className="w-3 h-3 text-[var(--color-safety-warning)]" />
          <span>AWaRe: WATCH</span>
        </span>
      );
    }
    return (
      <span className="inline-flex items-center space-x-1 px-2.5 py-0.5 rounded-full text-[10px] font-semibold bg-[var(--color-safety-critical-bg)] text-[var(--color-safety-critical)] border border-[var(--color-safety-critical-border)]">
        <AlertTriangle className="w-3 h-3 text-[var(--color-safety-critical)]" />
        <span>AWaRe: RESERVE</span>
      </span>
    );
  };

  return (
    <div className="p-5 rounded-[var(--radius-lg)] bg-slate-surface border border-slate-border space-y-4">
      <div className="flex items-center justify-between border-b border-slate-border-subtle pb-3">
        <div className="flex items-center space-x-2">
          <Layers className="w-4 h-4 text-[var(--color-clinical-400)]" />
          <h3 className="text-xs font-semibold uppercase tracking-wider text-slate-text-primary">
            Alternative Antimicrobial Recommendations
          </h3>
        </div>
        <span className="text-[10px] num-clinical text-slate-text-muted bg-slate-inset px-2 py-0.5 rounded border border-slate-border-subtle">
          {alternatives.length} Alternatives Synthesized
        </span>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-3.5">
        {alternatives.map((alt, idx) => (
          <div
            key={`${alt.antibiotic_name}-${idx}`}
            className="p-4 rounded-[var(--radius-md)] bg-slate-inset border border-slate-border-subtle space-y-2.5 flex flex-col justify-between"
          >
            <div className="space-y-1.5">
              <div className="flex items-center justify-between gap-2">
                <span className="font-bold text-sm text-slate-text-primary flex items-center">
                  <Pill className="w-4 h-4 mr-1.5 text-[var(--color-clinical-400)]" />
                  {alt.antibiotic_name}
                </span>
                {getAwareBadge(alt.guideline_category)}
              </div>

              <p className="text-xs text-slate-text-secondary leading-relaxed font-sans">
                {alt.reason}
              </p>
            </div>

            {/* Dosage & Duration spec */}
            <div className="pt-2 border-t border-slate-border-subtle text-[11px] text-slate-text-muted flex flex-wrap items-center justify-between gap-2 num-clinical">
              <span>{alt.dosage_notes || 'Standard therapeutic dose'}</span>
              <span className="font-semibold text-slate-text-secondary">
                Rank #{alt.ranking || idx + 2} • Confidence: {(alt.confidence || 'MODERATE').toUpperCase()}
              </span>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
