create table if not exists public.patient_records (
    id text primary key,
    owner_user_id uuid not null references auth.users(id) on delete restrict,
    hospital_id uuid not null references public.hospitals(id) on delete cascade,
    name text,
    date_of_birth text,
    sex text,
    demographics jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_patient_records_owner on public.patient_records(owner_user_id);

create table if not exists public.patient_history_events (
    id bigint generated by default as identity primary key,
    patient_id text not null references public.patient_records(id) on delete cascade,
    owner_user_id uuid not null references auth.users(id) on delete restrict,
    event_type text not null,
    summary text not null,
    payload jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists idx_patient_history_events_owner on public.patient_history_events(owner_user_id);
create index if not exists idx_patient_history_events_patient on public.patient_history_events(patient_id);

alter table public.patient_records enable row level security;
alter table public.patient_history_events enable row level security;

create policy patient_records_owner_read on public.patient_records
    for select using (owner_user_id = auth.uid());
create policy patient_records_owner_write on public.patient_records
    for all using (owner_user_id = auth.uid()) with check (owner_user_id = auth.uid());
create policy patient_history_owner_read on public.patient_history_events
    for select using (owner_user_id = auth.uid());
create policy patient_history_owner_write on public.patient_history_events
    for insert with check (owner_user_id = auth.uid());